/* Generated By:JJTree: Do not edit this line. ASTBooleanExpression.java */

package org.opensails.viento.parser;

public class ASTBooleanExpression extends SimpleNode {
  public ASTBooleanExpression(int id) {
    super(id);
  }

  public ASTBooleanExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
