/* Generated By:JJTree: Do not edit this line. ASTBoolean.java */

package org.opensails.viento.parser;

public class ASTBoolean extends SimpleNode {
	protected boolean value;
	
	public ASTBoolean(int id) {
		super(id);
	}

	public ASTBoolean(Parser p, int id) {
		super(p, id);
	}
	
	public void setValue(String string) {
		this.value = Boolean.valueOf(string);
	}
	
	public boolean getValue() {
		return value;
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
