/* Generated By:JJTree: Do not edit this line. ASTEqual.java */

package org.opensails.viento.parser;

public class ASTEqual extends SimpleNode {
  public ASTEqual(int id) {
    super(id);
  }

  public ASTEqual(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
