/* Generated By:JJTree: Do not edit this line. ASTGreaterThanOrEqual.java */

package org.opensails.viento.parser;

public class ASTGreaterThanOrEqual extends SimpleNode {
  public ASTGreaterThanOrEqual(int id) {
    super(id);
  }

  public ASTGreaterThanOrEqual(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
