/* Generated By:JJTree: Do not edit this line. ASTList.java */

package org.opensails.viento.parser;

public class ASTList extends SimpleNode {
  public ASTList(int id) {
    super(id);
  }

  public ASTList(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
