/* Generated By:JJTree: Do not edit this line. ASTMapEntry.java */

package org.opensails.viento.parser;

public class ASTMapEntry extends SimpleNode {
  public ASTMapEntry(int id) {
    super(id);
  }

  public ASTMapEntry(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
