/* Generated By:JJTree: Do not edit this line. ASTNumber.java */

package org.opensails.viento.parser;

public class ASTNumber extends SimpleNode {
	protected int value;
	public ASTNumber(int id) {
		super(id);
	}

	public ASTNumber(Parser p, int id) {
		super(p, id);
	}
	
	public int getValue() {
		return value;
	}
	
	public void setValue(String string) {
		this.value = Integer.parseInt(string);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
