/* Generated By:JJTree: Do not edit this line. ASTNotEqual.java */

package org.opensails.viento.parser;

public class ASTNotEqual extends SimpleNode {
  public ASTNotEqual(int id) {
    super(id);
  }

  public ASTNotEqual(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
