/* Generated By:JJTree: Do not edit this line. ASTStringBlock.java */

package org.opensails.viento.parser;

public class ASTStringBlock extends SimpleNode {
  public ASTStringBlock(int id) {
    super(id);
  }

  public ASTStringBlock(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
