/* Generated By:JJTree: Do not edit this line. ASTString.java */

package org.opensails.viento.parser;

public class ASTString extends SimpleNode {
    protected String value;
    
    public ASTString(int id) {
        super(id);
    }

    public ASTString(Parser p, int id) {
        super(p, id);
    }
    
    public String getValue() {
        return value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    /** Accept the visitor. * */
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
