/* Generated By:JJTree: Do not edit this line. ASTText.java */

package org.opensails.viento.parser;

public class ASTText extends SimpleNode {
	protected String contents;

	public ASTText(int id) {
		super(id);
	}

	public ASTText(Parser p, int id) {
		super(p, id);
	}

	public String getContents() {
		return contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
